name: Renovate Global Bot
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Run Renovate
        run: renovate
        env:
          RENOVATE_PLATFORM: gitea
          RENOVATE_ENDPOINT: https://gitea.bk.glpx.pro/api/v1
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          RENOVATE_CONFIG_FILE: config.js
          RENOVATE_AUTODISCOVER: "true"
          LOG_LEVEL: debug
