name: Reusable Security Sweep
on:
  workflow_call:


permissions:
  contents: read

concurrency:
  group: ${{ gitea.workflow }}-${{ gitea.head_ref || gitea.ref }}
  cancel-in-progress: true

jobs:
  gosec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Run Gosec Security Scanner
        uses: securego/gosec@v2
        with:
          args: ./...
